name: Terraform

on:
  push:
    branches:
      - '**'

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint
        run: .github/workflows/scripts/lint.sh
      
      - name: Validate
        run: .github/workflows/scripts/validate.sh
      
      - name: Comply
        run: .github/workflows/scripts/comply.sh 

  terraform-plan-dev:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Store AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Plan
        run: |
          .github/workflows/scripts/assume-role.sh "arn:aws:iam::767397886223:role/DeploymentRole"
          .github/workflows/scripts/plan.sh
        env:
          CONFIG: dev
      
      - name: upload-dev-plan
        uses: actions/upload-artifact@v4
        with:
          name: dev.plan
          path: terraform/config/dev.plan
  
  terraform-apply-dev:
    needs: terraform-plan-dev
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev
    env:
      config: dev
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Store AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: download-dev-plan
        uses: actions/download-artifact@v4
        with:
          name: dev.plan
          path: terraform/config
      
      - name: Apply
        run: |
          .github/workflows/scripts/assume-role.sh "arn:aws:iam::767397886223:role/DeploymentRole"
          .github/workflows/scripts/apply.sh
        env:
          CONFIG: dev
  
  node-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: NPM Install
        run: make npm_install

      - name: NPM Build
        run: make npm_build

      - name: Upload site to S3
        needs: terraform-apply-dev
        #if: github.ref == 'refs/heads/main'
        run: |
          .github/workflows/scripts/assume-role.sh "arn:aws:iam::767397886223:role/DeploymentRole"
          .github/workflows/scripts/upload.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET_ACCESS_KEY }}