name: Terraform

on:
  push:
    branches:
      - '**'

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint
        run: .github/workflows/scripts/lint.sh
      
      - name: Validate
        run: .github/workflows/scripts/validate.sh
      
      - name: Comply
        run: .github/workflows/scripts/comply.sh
      
  terraform-plan-dev:
    runs-on: ubuntu-latest
    needs: terraform-checks
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Plan
        run: |
          . .github/workflows/scripts/assume-role.sh "arn:aws:iam::767397886223:role/DeploymentRole"
          . .github/workflows/scripts/plan.sh
        env:
          CONFIG: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
      
      - name: upload-dev-plan
        uses: actions/upload-artifact@v4
        with:
          name: dev.plan
          path: terraform/config/dev.plan

  terraform-apply-dev:
    needs: terraform-plan-dev
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev
    env:
      config: dev
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: download-dev-plan
        uses: actions/download-artifact@v4
        with:
          name: dev.plan
          path: terraform/config
      
      - name: Apply
        run: |
          . .github/workflows/scripts/assume-role.sh "arn:aws:iam::767397886223:role/DeploymentRole"
          . .github/workflows/scripts/apply.sh
        env:
          CONFIG: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2

  frontend-build:
    runs-on: ubuntu-latest
    needs: terraform-checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: NPM Install
        run: make npm_install

      - name: NPM Build
        run: make npm_build
      
      - name: Upload frontend to pipeline
        uses: actions/upload-artifact@v4
        with:
          name: frontend
          path: frontend/build/*
  
  # Doesnt do anything yet other than echo the CONFIG var
  upload-frontend-to-s3:
    runs-on: ubuntu-latest
    needs: [ terraform-apply-dev, frontend-build ]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download frontend from pipeline
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: frontend/build

      - name: Upload site to S3
        run: |
          . .github/workflows/scripts/assume-role.sh "arn:aws:iam::767397886223:role/DeploymentRole"
          . .github/workflows/scripts/upload.sh
        env:
          CONFIG: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2