name: Terraform

on:
  push:
    branches:
      - 'cwilson/local-development-make'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint
        run: workflows/scripts/lint.sh