name: Terraform

on:
  push:
    branches:
      - '**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Store AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Lint
        run: .github/workflows/scripts/lint.sh
      
      # - name: Validate
      #   run: .github/workflows/scripts/validate.sh

      - name: Plan
        run: |
          ROLE_ARN="arn:aws:iam::767397886223:role/DeploymentRole"
          aws sts assume-role --role-arn $ROLE_ARN --role-session-name GitHubActionsSession > assumed-role.json
          export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId assumed-role.json)
          export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey assumed-role.json)
          export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken assumed-role.json)
          .github/workflows/scripts/plan.sh
        env:
          CONFIG: dev
