name: Terraform

on:
  push:
    branches:
      - '*'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Lint
        run: workflows/scripts/lint.sh